/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PinSetupRouteImport } from './routes/pin-setup'
import { Route as PinRouteImport } from './routes/pin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AgeRouteImport } from './routes/age'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReelsRouteImport } from './routes/_app.reels'
import { Route as AppLikedRouteImport } from './routes/_app.liked'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppSavedRouteImport } from './routes/_app.saved'
import { Route as AppAboutRouteImport } from './routes/_app.about'
import { Route as AppShopRouteImport } from './routes/_app.shop'

const PinSetupRoute = PinSetupRouteImport.update({
  id: '/pin-setup',
  path: '/pin-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PinRoute = PinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgeRoute = AgeRouteImport.update({
  id: '/age',
  path: '/age',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReelsRoute = AppReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AppRoute,
} as any)
const AppLikedRoute = AppLikedRouteImport.update({
  id: '/liked',
  path: '/liked',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/age': typeof AgeRoute
  '/login': typeof LoginRoute
  '/pin': typeof PinRoute
  '/pin-setup': typeof PinSetupRoute
  '/home': typeof AppHomeRoute
  '/liked': typeof AppLikedRoute
  '/reels': typeof AppReelsRoute
  '/saved': typeof AppSavedRoute
  '/settings': typeof AppSettingsRoute
  '/about': typeof AppAboutRoute
  '/shop': typeof AppShopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/age': typeof AgeRoute
  '/login': typeof LoginRoute
  '/pin': typeof PinRoute
  '/pin-setup': typeof PinSetupRoute
  '/home': typeof AppHomeRoute
  '/liked': typeof AppLikedRoute
  '/reels': typeof AppReelsRoute
  '/saved': typeof AppSavedRoute
  '/settings': typeof AppSettingsRoute
  '/about': typeof AppAboutRoute
  '/shop': typeof AppShopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/age': typeof AgeRoute
  '/login': typeof LoginRoute
  '/pin': typeof PinRoute
  '/pin-setup': typeof PinSetupRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/liked': typeof AppLikedRoute
  '/_app/reels': typeof AppReelsRoute
  '/_app/saved': typeof AppSavedRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/about': typeof AppAboutRoute
  '/_app/shop': typeof AppShopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/age'
    | '/login'
    | '/pin'
    | '/pin-setup'
    | '/home'
    | '/liked'
    | '/reels'
    | '/saved'
    | '/settings'
    | '/about'
    | '/shop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/age'
    | '/login'
    | '/pin'
    | '/pin-setup'
    | '/home'
    | '/liked'
    | '/reels'
    | '/saved'
    | '/settings'
    | '/about'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/age'
    | '/login'
    | '/pin'
    | '/pin-setup'
    | '/_app/home'
    | '/_app/liked'
    | '/_app/reels'
    | '/_app/saved'
    | '/_app/settings'
    | '/_app/about'
    | '/_app/shop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AgeRoute: typeof AgeRoute
  LoginRoute: typeof LoginRoute
  PinRoute: typeof PinRoute
  PinSetupRoute: typeof PinSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pin-setup': {
      id: '/pin-setup'
      path: '/pin-setup'
      fullPath: '/pin-setup'
      preLoaderRoute: typeof PinSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pin': {
      id: '/pin'
      path: '/pin'
      fullPath: '/pin'
      preLoaderRoute: typeof PinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/age': {
      id: '/age'
      path: '/age'
      fullPath: '/age'
      preLoaderRoute: typeof AgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reels': {
      id: '/_app/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof AppReelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/liked': {
      id: '/_app/liked'
      path: '/liked'
      fullPath: '/liked'
      preLoaderRoute: typeof AppLikedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved': {
      id: '/_app/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shop': {
      id: '/_app/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppLikedRoute: typeof AppLikedRoute
  AppReelsRoute: typeof AppReelsRoute
  AppSavedRoute: typeof AppSavedRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppAboutRoute: typeof AppAboutRoute
  AppShopRoute: typeof AppShopRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppLikedRoute: AppLikedRoute,
  AppReelsRoute: AppReelsRoute,
  AppSavedRoute: AppSavedRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppAboutRoute: AppAboutRoute,
  AppShopRoute: AppShopRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AgeRoute: AgeRoute,
  LoginRoute: LoginRoute,
  PinRoute: PinRoute,
  PinSetupRoute: PinSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
